### ISSUE TITLE
MAC sierra build fail

### ISSUE THREAD

**Issue by scarfunk** [weirdmeetup/koalabot#14]
```
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/sukkyu/.node-gyp/6.6.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  c++ '-DNODE_GYP_MODULE_NAME=node-icu-charset-detector' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/sukkyu/.node-gyp/6.6.0/include/node -I/Users/sukkyu/.node-gyp/6.6.0/src -I/Users/sukkyu/.node-gyp/6.6.0/deps/uv/include -I/Users/sukkyu/.node-gyp/6.6.0/deps/v8/include -I../../nan -I/opt/local/include -I/usr/local/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o.d.raw   -c -o Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o ../node-icu-charset-detector.cpp
In file included from ../node-icu-charset-detector.cpp:2:
../../nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/sukkyu/.nvm/versions/node/v6.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/Users/sukkyu/.nvm/versions/node/v6.6.0/bin/node" "/Users/sukkyu/.nvm/versions/node/v6.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sukkyu/koalabot/node_modules/node-icu-charset-detector
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm verb lifecycle node-icu-charset-detector@0.1.4~install: unsafe-perm in lifecycle true
npm verb lifecycle node-icu-charset-detector@0.1.4~install: PATH: /Users/sukkyu/.nvm/versions/node/v6.6.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/sukkyu/koalabot/node_modules/node-icu-charset-detector/node_modules/.bin:/Users/sukkyu/koalabot/node_modules/.bin:/Users/sukkyu/.nvm/versions/node/v6.6.0/bin:/Users/sukkyu/.nvm/versions/node/v6.6.0/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Library/TeX/texbin:/Users/sukkyu/.yadr/bin:/Users/sukkyu/.yadr/bin/yadr
npm verb lifecycle node-icu-charset-detector@0.1.4~install: CWD: /Users/sukkyu/koalabot/node_modules/node-icu-charset-detector
npm info lifecycle node-icu-charset-detector@0.1.4~install: Failed to exec install script
npm WARN install:node-icu-charset-detector@0.1.4 node-icu-charset-detector@0.1.4 install: `node-gyp rebuild`
npm WARN install:node-icu-charset-detector@0.1.4 Exit status 1
npm verb install:node-icu-charset-detector@0.1.4 Error: node-icu-charset-detector@0.1.4 install: `node-gyp rebuild`
npm verb install:node-icu-charset-detector@0.1.4 Exit status 1
npm verb install:node-icu-charset-detector@0.1.4     at EventEmitter.<anonymous> (/Users/sukkyu/.nvm/versions/node/v6.6.0/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
npm verb install:node-icu-charset-detector@0.1.4     at emitTwo (events.js:106:13)
npm verb install:node-icu-charset-detector@0.1.4     at EventEmitter.emit (events.js:191:7)
npm verb install:node-icu-charset-detector@0.1.4     at ChildProcess.<anonymous> (/Users/sukkyu/.nvm/versions/node/v6.6.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
npm verb install:node-icu-charset-detector@0.1.4     at emitTwo (events.js:106:13)
npm verb install:node-icu-charset-detector@0.1.4     at ChildProcess.emit (events.js:191:7)
npm verb install:node-icu-charset-detector@0.1.4     at maybeClose (internal/child_process.js:877:16)
npm verb install:node-icu-charset-detector@0.1.4     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

nvm v6.6.0 이고

brew install icu4c
brew link icu4c --force
로 했는데도 해결이 안되는군영...

**Comment by scarfunk** [comment]
차선책(workaround)
LTS 4로 npm install
실행은 node V6 bin/hubot --name koalabot
- hubot-scripts.json 파일 삭제 해줘야 하네요....

koalabot> koalabot hi
koalabot> :koala: bro

성공 확인.

**Comment by haruair** [comment]
6대로 올리니 바로 비슷한 문제가 발생하네요. 그런데 node-icu-charset-detector를 node-irc에서 사용하는데 optional dep이라서 설치하지 않아도 통과되야 하는데 이상하군요!

**Comment by haruair** [comment]
문제가 되던 hubot-irc를 제거했습니다. 이제 v6에서도 문제 없이 사용하실 수 있을겁니다.

**Comment by scarfunk** [comment]
앗 감사합니다!
